default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
          exclude: ^helm/
        - id: check-added-large-files
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: check-ast
        - id: double-quote-string-fixer
        - id: detect-private-key
        - id: detect-aws-credentials
        - id: debug-statements
        - id: requirements-txt-fixer
        - id: check-json
